added support for private keys in the ftp component
clientIO/appmixer-connectors pull request #139
Opened 2024-07-31 13:44 UTC by lucvankessel

We were in need of a key option in the FTP component.
This is the implementation i came up with.
I have tested it  that it still works with password and the new key option.
Let me know if there are things you would like to see different or changed.

2024-07-31 14:39 UTC, lucvankessel commented on src/appmixer/utils/ftp/client.js
> +        return ['yes', 'implicit'].includes(secure);
the `''` the default to be the secure option

2024-08-01 11:57 UTC, jirihofman commented
Thank you for your contribution @lucvankessel 🎉 . We will review the change some time next week, even though it looks good at first glance.

2024-08-07 13:20 UTC, jirihofman requested changes
Minor wording update

2024-08-07 13:20 UTC, jirihofman commented on src/appmixer/utils/ftp/client.js
> +                throw new Error('Cant use the secure option in combination with a private key');
```suggestion
                throw new Error('Private key can be used only for SFTP');
```

2024-08-07 13:20 UTC, jirihofman commented on src/appmixer/utils/ftp/auth.js
> +                tooltip: 'Private key; either use this or the password field, this only works with sFTP. PEM is the only supported format for keys that can be used.'
```suggestion
                tooltip: 'Private key; either use this or the password field. This only works with SFTP. PEM is the only supported format for keys that can be used.'
```

2024-08-07 14:15 UTC, lucvankessel commented on src/appmixer/utils/ftp/auth.js
> +                tooltip: 'Private key; either use this or the password field, this only works with sFTP. PEM is the only supported format for keys that can be used.'
@jirihofman implemeted both changes

2024-08-08 11:37 UTC, jirihofman approved these changes
Great, thank you @lucvankessel

I just bumped the version and added changelog entry

2024-08-08 11:38 UTC, merged