Servicenow
clientIO/appmixer-connectors pull request #163
Opened 2024-08-23 10:41 UTC by vtalas

new trigger: 

- [x] **NewRecord**
- [x]  docs
 - https://github.com/clientIO/appmixer-docs-gitbook/pull/26

2024-08-26 07:39 UTC, jirihofman requested changes

2024-08-26 07:39 UTC, jirihofman commented on src/appmixer/servicenow/routes.js
> +                    context.log('error', 'Missing type property.', req.payload);
This gives me an error:
![image](https://github.com/user-attachments/assets/44bc0ece-1268-4065-8d3f-213612d5d1a8)

```suggestion
                    context.log({ step: 'error', message: 'Missing type property.', payload: req.payload});
```

2024-08-26 07:39 UTC, jirihofman commented on src/appmixer/servicenow/record/UpdateRecord/component.json
> +
why the new line? 🙂

2024-08-27 12:21 UTC, vtalas commented
@jirihofman fixed

2024-08-27 12:51 UTC, jirihofman approved these changes

2024-08-27 12:51 UTC, merged