Major upgrade of Zendesk Tickets
clientIO/appmixer-connectors pull request #181
Opened 2024-09-12 20:34 UTC by DavidDurman

2024-09-13 06:07 UTC, jirihofman approved these changes

2024-09-25 20:10 UTC, jirihofman requested changes

2024-09-25 20:10 UTC, jirihofman commented on src/appmixer/zendesktickets/package-lock.json
We don't use `package-lock.json` files yet. Please remove it.

2024-10-01 17:44 UTC, jirihofman approved these changes

2024-10-04 12:36 UTC, vtalas reviewed
@DavidDurman  quotas are missing, there should be at least some quotas set

2024-10-04 15:00 UTC, DavidDurman commented
The rate limits of Zendesk are very complicated and also depend on the account tier. I'm not sure how this can be implemented using our current quotas mechanism. See https://developer.zendesk.com/api-reference/introduction/rate-limits/#zendesk-suite-plan-limits

2024-10-10 07:32 UTC, vtalas commented
- [ ] add at least some basic quotas

2024-10-15 15:22 UTC, vtalas requested changes
apply quotas in compoent.json files

2024-10-17 13:34 UTC, vtalas approved these changes

2024-10-17 13:35 UTC, merged

2024-10-21 01:26 UTC, RamBachkheti commented
@vtalas: The backoffice displays four different tickets labeled 'Zendesk.' Could you please let me know which one I should use? Additionally, could you remove any duplicates to avoid confusion?

<img width="1461" alt="Screenshot 2024-10-21 at 6 41 13 AM" src="https://github.com/user-attachments/assets/1e14d33f-7a52-410a-9d62-481d56809067">

2024-10-21 09:23 UTC, vtalas commented
@RamBachkheti  it't this one: 
![image](https://github.com/user-attachments/assets/da251965-8801-4a4a-b795-bde65532fd34)

we're going to remove deprecated version from the marketplace

2024-10-22 05:59 UTC, RamBachkheti commented
Issue 1: [CreateUser] Getting "error:DatabaseConflict", please see the following image:
- <img width="1462" alt="Screenshot 2024-10-22 at 11 27 33 AM" src="https://github.com/user-attachments/assets/b28f495e-b021-49a0-a554-e2999187711f">
<hr>

Issue 2: [UpdateOrganization] "Domain Names" should have validation message when domain formate doesn't match, please see the following image:
<img width="1462" alt="Screenshot 2024-10-22 at 11 26 22 AM" src="https://github.com/user-attachments/assets/09dcf26d-4d67-4f41-80c4-e6ccac380dec">

2024-11-19 12:25 UTC, DavidDurman commented
@vtalas why is Zendesk requiring me to enter clientID/secret on QA? This wasn't the case before and the standard OAuth was working fine:

![image](https://github.com/user-attachments/assets/6c7bcfbb-9ae6-43a3-a56d-1c36efb3b3c1)

2024-11-19 12:34 UTC, vtalas commented
> @vtalas why is Zendesk requiring me to enter clientID/secret on QA? This wasn't the case before and the standard OAuth was working fine:
> 
> ![image](https://private-user-images.githubusercontent.com/125717/387651562-6c7bcfbb-9ae6-43a3-a56d-1c36efb3b3c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMTk4MzksIm5iZiI6MTczMjAxOTUzOSwicGF0aCI6Ii8xMjU3MTcvMzg3NjUxNTYyLTZjN2JjZmJiLTlhZTYtNDNhMy1hNTZkLTFjMzZlZmIzYjNjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQxMjMyMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NmI2NzlmMGJkYTdhMzk5ZWY5YTE1MzhkN2RjOTVlNGViMWIzZGU1YWU5ZjIyYjE5NGZkYjBkOTJkMmQyMmJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qCVPSFJljYb0AHV4Rxo6NkEHOAh3UvUandw7eJPWoG8)

@DavidDurman  it's due to bug on in the authub (https://github.com/clientIO/appmixer-core/issues/2640), when the `globasKeys` is set to `true`, it won't ask for the clientId & secret.

2024-11-19 13:07 UTC, DavidDurman commented
@RamBachkheti do you have repro steps to Issue nr. 1? It's working fine for me with these values:

![image](https://github.com/user-attachments/assets/74a1ca47-946b-4a14-b9c9-e9009a4f041e)

2024-11-19 14:06 UTC, vtalas commented
> Issue 2: I don't think we have a way to define a validation for "comma separated list of domains". What do you think @vtalas .

Surely we have, you can use the `pattern`  (regex). On the other hand, the velation message is not pretty in that case 
![image](https://github.com/user-attachments/assets/722c396f-e8ed-4218-8dc5-52c687eb1744)

Also even it's great to catch as many errors as possible at the design phase I don't think it's crucial to introduce a regex in this case. @DavidDurman  you decide. I would rather consider including this note  
![image](https://github.com/user-attachments/assets/9089ed40-fedd-4675-9fb8-d23402b06e22)

https://developer.zendesk.com/api-reference/ticketing/organizations/organizations/#update-organization