Fix for error "Cannot read properties of undefined (reading 'id')"
clientIO/appmixer-connectors pull request #218
Opened 2024-10-09 09:12 UTC by sayam-nasir

In the Triggers NewRow, UpdatedRow and DeletedRow
The SQL Query needs project ID. which was being fetched using a function getProjectId. In this function we were trying to find the project ID out of a list of all projects as whichever projects numericid would match the first part of clientID, we would take that project's projectID.

This approach was not working as none of the projects' numeric ID was matching anything in the list of projects

Hence, now an input field of select type has been introduced in the triggers which helps the user to select one project out of all the projects in their bigQuery playground and then the query is run on this project's ID.

2024-10-09 11:37 UTC, jirihofman requested changes
I think we should also remove the `getProjectId` function.

2024-10-09 13:46 UTC, sayam-nasir commented
removed the function getProjectId because it is not used anywhere anymore

2024-10-09 14:02 UTC, vtalas requested changes
projectId  should be marked as `required`

2024-10-10 07:25 UTC, jirihofman approved these changes

2024-10-10 07:26 UTC, merged