Microsoft.Mail.CreateDraft Component
clientIO/appmixer-connectors pull request #239
Opened 2024-10-21 13:53 UTC by sayam-nasir

2024-10-23 14:02 UTC, vtalas requested changes

2024-10-23 14:02 UTC, vtalas commented on src/appmixer/microsoft/mail/CreateDraft/component.json
> +                "inputs": {
there are more in properties in the `message` type [spescs](https://learn.microsoft.com/en-us/graph/api/resources/message?view=graph-rest-1.0#properties). Can we add more? at least bcc (comparing with gmail.CreateDraft)

2024-10-29 13:36 UTC, sayam-nasir commented on src/appmixer/microsoft/mail/CreateDraft/component.json
> +                "required": ["toRecipients", "content"]
@vtalas this is made required to keep the uniformity with the SendEmail component as this was discussed similarly in Gmail CreateDraft and SendEmail case

2024-10-30 07:48 UTC, vtalas approved these changes

2024-10-30 07:49 UTC, merged