Google.Analytics (upgrade) version 4
clientIO/appmixer-connectors pull request #277
Opened 2024-11-12 13:20 UTC by ZbynekPelunek

This is an upgrade from Google Analytics 3 to 4. As found out, Google completely changed a lot of things and made a public REST API which is called `v1beta` or `v1alpha` . The Beta is considered stable with no possible breaking changes.

The upgrade will remove old components and add new ones:

- [ ] Create Events (this one is not using `v1beta` route)
- [ ] Generate Report

2024-11-18 11:00 UTC, ZbynekPelunek commented
When you create an event using the Create Event component, you can find the event on GA4 website here:
![Screenshot 2024-11-18 115906](https://github.com/user-attachments/assets/1d8fbec4-4023-4515-9de6-853841abd096)

2024-11-18 13:52 UTC, vtalas requested changes

2024-11-18 13:52 UTC, vtalas commented on src/appmixer/google/analytics/CreateEvents/CreateEvents.js
> +        await context.httpRequest({
there has to be the `context.sendJson`, even with empty object. without it, the flow will stuck on the CreateEvent component

2024-11-18 13:52 UTC, vtalas commented on src/appmixer/google/analytics/CreateEvents/component.json
> +        "service": "appmixer:google:analytics"
is the authentication needed? there is no authenticated call in the implementation

2024-11-18 13:52 UTC, vtalas commented on src/appmixer/google/analytics/CreateEvents/CreateEvents.js
> +        const qeuryParams = {
typo

2024-11-19 14:55 UTC, vtalas approved these changes

2024-11-19 14:55 UTC, merged