AzureDocumentIntelligence.ClassifyDocument - better tooltips
clientIO/appmixer-connectors pull request #314
Opened 2024-12-16 05:13 UTC by ZbynekPelunek

2024-12-16 08:37 UTC, vtalas requested changes
@ZbynekPelunek  please update the bundle.json as well

2024-12-16 08:57 UTC, ZbynekPelunek commented
> @ZbynekPelunek please update the bundle.json as well

Alright, I wasn't sure if I should do it as it is only tooltip change, thanks for the confirmation.

2024-12-17 11:26 UTC, jirihofman approved these changes

2024-12-17 11:26 UTC, jirihofman commented on src/appmixer/azuredocumentintelligence/classifiers/ClassifyDocumentFromStream/ClassifyDocumentFromStream.js
> +        options = {
Can `options` be const?

```suggestion
        const fileInfo = await context.getFileInfo(fileId);
        const fileStream = await context.getFileReadStream(fileId);
        const options = {
```

2024-12-17 15:49 UTC, vtalas approved these changes

2024-12-17 15:49 UTC, merged