utils.csv.AddRows
clientIO/appmixer-connectors pull request #86
Opened 2024-04-25 07:17 UTC by harshaio

- A new component `AddRows` to support batch insertion of rows

2024-04-25 09:27 UTC, vtalas requested changes
I noticed there are not much changes comparing the `addRows` and `addRows` in tge CSVProcessor.js. It should be fairly easy to refactor to the use just one method, `addRows` is the obvious choice for me. 

maybe the processor.addRow might be refactored as something like 
```
    async addRow({ row, rowWithColumns }, closure) {
        this.addRows([row], closure);
    }
```


Also, I think the `context` is undefined here: 
https://github.com/clientIO/appmixer-connectors/blob/dev/src/appmixer/utils/csv/CSVProcessor.js#L384

2024-04-25 09:27 UTC, vtalas commented on src/appmixer/utils/csv/AddRows/component.json
> +                        "tooltip": "The rows to append."
it's not clear what format should we use. It has to be a JSON array so it would good to mention it, here, maybe with a simple example

2024-04-25 09:27 UTC, vtalas commented on src/appmixer/utils/csv/AddRows/AddRows.js
> +        const { withHeaders } = context.properties;
it's not used here (there is no definition in the compoentn.json either), I think we can remove `withHeaders` completely

2024-04-25 09:31 UTC, vtalas commented on src/appmixer/utils/csv/AddRows/AddRows.js
> +        const { withHeaders } = context.properties;
btw, why is `withHeaders` is not implemented here?

2024-04-26 08:08 UTC, vtalas commented on src/appmixer/utils/csv/bundle.json
> +  "version": "1.2.6",
should be 1.3.0 as we're adding new features

2024-04-26 08:25 UTC, vtalas commented
@harshaio  please add the     `"engine": ">=5.0",` as it uses `context.replaceFileStream` introduced in the version 5 (same as here https://github.com/clientIO/appmixer-connectors/blob/dev/src/appmixer/google/youtube/bundle.json#L4)

2024-04-26 08:25 UTC, jirihofman requested changes
Add a `test-flow.json` please. Ideally for both `AddRow` and `AddRows`.

2024-04-26 09:59 UTC, vtalas commented
please add the quota for user:

```
        {
            limit: 5,
            throttling: 'limit-concurrency',
            queueing: 'fifo',
            resource: 'loadFiles',
            scope: 'userId'
        },
```

2024-05-02 07:40 UTC, vtalas approved these changes

2024-05-02 07:40 UTC, merged